\c postgres

DROP DATABASE IF EXISTS estudantesdb;

CREATE DATABASE estudantesdb;

\c estudantesdb;

CREATE TABLE avaliacao (
    id SERIAL PRIMARY KEY,
    nota INTEGER NOT NULL,
    professor VARCHAR(255) NOT NULL,
    materia VARCHAR(255) NOT NULL,
    sala VARCHAR(255) NOT NULL
);

CREATE TABLE estudante (
    id SERIAL PRIMARY KEY,
    name_estudante VARCHAR(255) NOT NULL,
    photo TEXT,
    avaliacao_id INTEGER REFERENCES avaliacao(id) ON DELETE CASCADE
);

INSERT INTO avaliacao (nota, professor, materia, sala) VALUES
    (2, 'Camila', 'Matemática', '101'),
    (7, 'Carlos', 'História', '102'),
    (9, 'Renata', 'Biologia', '103'),
    (5, 'Lucas', 'Química', '104'),
    (7, 'Beatriz', 'Física', '105'),
    (1, 'Felipe', 'Geografia', '106'),
    (3, 'Fernanda', 'Educação Física', '107'),
    (2, 'Camila', 'Matemática', '101'),
    (10, 'Felipe', 'História', '102'),
    (3, 'Beatriz', 'Biologia', '103'),
    (6, 'Agiota', 'Química', '104'),
    (0, 'Renata', 'Física', '105'),
    (6, 'Fernanda', 'Geografia', '106'),
    (1, 'Carlos', 'Educação Física', '107'),
    (2, 'Eduardo', 'Matemática', '101'),
    (10, 'Beatriz', 'História', '102'),
    (4, 'Felipe', 'Biologia', '103'),
    (0, 'Agiota', 'Química', '104'),
    (0, 'Lucas', 'Física', '105'),
    (3, 'Renata', 'Geografia', '106'),
    (7, 'Beatriz', 'Educação Física', '107'),
    (0, 'Renata', 'Matemática', '101'),
    (4, 'Beatriz', 'História', '102'),
    (5, 'Renata', 'Biologia', '103'),
    (9, 'Felipe', 'Química', '104'),
    (1, 'Camila', 'Física', '105'),
    (6, 'Agiota', 'Geografia', '106'),
    (5, 'Fernanda', 'Educação Física', '107'),
    (5, 'Beatriz', 'Matemática', '101'),
    (7, 'Eduardo', 'História', '102'),
    (0, 'Thiago', 'Química', '104'),
    (5, 'Eduardo', 'Física', '105'),
    (7, 'Renata', 'Geografia', '106'),
    (6, 'Lucas', 'Educação Física', '107'),
    (4, 'Carlos', 'Matemática', '101'),
    (1, 'Camila', 'Biologia', '103'),
    (5, 'Renata', 'Química', '104'),
    (5, 'Eduardo', 'Física', '105'),
    (0, 'Felipe', 'Geografia', '106'),
    (4, 'Carlos', 'Educação Física', '107'),
    (7, 'Carlos', 'Matemática', '101'),
    (5, 'Felipe', 'História', '102'),
    (8, 'Beatriz', 'Biologia', '103'),
    (2, 'Carlos', 'Química', '104'),
    (3, 'Fernanda', 'Física', '105'),
    (7, 'Tavin', 'Geografia', '106'),
    (5, 'Felipe', 'Educação Física', '107'),
    (3, 'Carlos', 'Matemática', '101'),
    (4, 'Beatriz', 'História', '102'),
    (3, 'Felipe', 'Biologia', '103'),
    (6, 'Renata', 'Química', '104'),
    (3, 'Carlos', 'Física', '105'),
    (3, 'Lucas', 'Geografia', '106'),
    (6, 'Renata', 'Educação Física', '107'),
    (3, 'Eduardo', 'Matemática', '101'),
    (0, 'Camila', 'História', '102'),
    (3, 'Beatriz', 'Biologia', '103'),
    (1, 'Felipe', 'Química', '104'),
    (3, 'Lucas', 'Física', '105'),
    (9, 'Carlos', 'Geografia', '106'),
    (4, 'Camila', 'Matemática', '101'),
    (0, 'Renata', 'História', '102'),
    (6, 'Lucas', 'Biologia', '103'),
    (3, 'Lucas', 'Química', '104'),
    (10, 'Lucas', 'Física', '105'),
    (9, 'Felipe', 'Geografia', '106'),
    (10, 'Renata', 'Educação Física', '107'),
    (3, 'Beatriz', 'Matemática', '101'),
    (2, 'Tavin', 'História', '102'),
    (9, 'Camila', 'Biologia', '103'),
    (4, 'Lucas', 'Química', '104'),
    (6, 'Camila', 'Física', '105'),
    (1, 'Fernanda', 'Geografia', '106'),
    (3, 'Tavin', 'Educação Física', '107'),
    (3, 'Camila', 'Matemática', '101'),
    (9, 'Camila', 'História', '102'),
    (2, 'Felipe', 'Biologia', '103'),
    (4, 'Lucas', 'Química', '104'),
    (7, 'Renata', 'Física', '105'),
    (7, 'Fernanda', 'Geografia', '106'),
    (6, 'Renata', 'Educação Física', '107'),
    (4, 'Beatriz', 'Matemática', '101'),
    (2, 'Renata', 'História', '102'),
    (2, 'Carlos', 'Biologia', '103'),
    (1, 'Renata', 'Química', '104'),
    (4, 'Lucas', 'Física', '105'),
    (0, 'Camila', 'Geografia', '106'),
    (10, 'Carlos', 'Educação Física', '107'),
    (7, 'Renata', 'Matemática', '101'),
    (4, 'Eduardo', 'História', '102'),
    (3, 'Beatriz', 'Biologia', '103'),
    (0, 'Camila', 'Química', '104'),
    (7, 'Eduardo', 'Física', '105'),
    (7, 'Lucas', 'Geografia', '106'),
    (0, 'Carlos', 'Educação Física', '107'),
    (4, 'Renata', 'Matemática', '101'),
    (9, 'Renata', 'História', '102'),
    (4, 'Renata', 'Biologia', '103'),
    (5, 'Lucas', 'Química', '104'),
    (4, 'Carlos', 'Física', '105');

INSERT INTO estudante (name_estudante, photo, avaliacao_id) VALUES
    ('Fernanda', '/images/fernanda.jpg', 1),
    ('Bruna', NULL, 2),
    ('Daniela', NULL, 3),
    ('Gabriel', NULL, 4),
    ('Roberto', NULL, 5),
    ('Leticia', NULL, 6),
    ('Gabriel', NULL, 7),
    ('Daniela', NULL, 8),
    ('Juliana', '/images/juliana.jpg', 9),
    ('Bruna', NULL, 10),
    ('Ana', NULL, 11),
    ('Daniela', NULL, 12),
    ('Juliana', NULL, 13),
    ('Larissa', NULL, 14),
    ('Juliana', NULL, 15),
    ('Roberto', NULL, 16),
    ('Gabriel', NULL, 17),
    ('Larissa', NULL, 18),
    ('Gabriel', NULL, 19),
    ('Daniela', NULL, 20),
    ('Paulo', NULL, 21),
    ('Gabriel', NULL, 22),
    ('Juliana', NULL, 23),
    ('João', NULL, 24),
    ('Afonso', NULL, 25),
    ('Ana', NULL, 26),
    ('Afonso', NULL, 27),
    ('Juliana', NULL, 28),
    ('Larissa', NULL, 29),
    ('Juliana', NULL, 30),
    ('Larissa', NULL, 31),
    ('Gabriel', NULL, 32),
    ('Roberto', NULL, 33),
    ('Afonso', NULL, 34),
    ('Gabriel', NULL, 35),
    ('Ana', NULL, 36),
    ('Gabriel', NULL, 37),
    ('Gabriel', NULL, 38),
    ('Gabriel', NULL, 39),
    ('Juliana', NULL, 40),
    ('Daniela', NULL, 41),
    ('Paulo', NULL, 42),
    ('Juliana', NULL, 43),
    ('Ana', NULL, 44),
    ('Daniela', NULL, 45),
    ('Paulo', NULL, 46),
    ('Leticia', NULL, 47),
    ('Juliana', NULL, 48),
    ('Ana', NULL, 49),
    ('Juliana', NULL, 50),
    ('Leticia', NULL, 51),
    ('Leticia', NULL, 52),
    ('Paulo', NULL, 53),
    ('Leticia', NULL, 54),
    ('Juliana', NULL, 55),
    ('Fernanda', '/images/fernanda.jpg', 56),
    ('Paulo', NULL, 57),
    ('Roberto', NULL, 58),
    ('Juliana', NULL, 59),
    ('João', NULL, 60),
    ('Ana', NULL, 61),
    ('Gabriel', NULL, 62),
    ('Juliana', NULL, 63),
    ('Afonso', NULL, 64),
    ('Fernanda', NULL, 65),
    ('João', NULL, 66),
    ('Leticia', NULL, 67),
    ('Bruna', NULL, 68),
    ('Juliana', NULL, 69),
    ('Larissa', NULL, 70),
    ('Larissa', NULL, 71),
    ('Gabriel', NULL, 72),
    ('Juliana', NULL, 73),
    ('Afonso', NULL, 74),
    ('Juliana', NULL, 75),
    ('João', NULL, 76),
    ('Bruna', NULL, 77),
    ('Juliana', NULL, 78),
    ('Afonso', NULL, 79),
    ('João', NULL, 80),
    ('Larissa', NULL, 81),
    ('Roberto', NULL, 82),
    ('Roberto', NULL, 83),
    ('Roberto', NULL, 84),
    ('Fernanda', NULL, 85),
    ('Roberto', NULL, 86),
    ('Gabriel', NULL, 87),
    ('Gabriel', NULL, 88),
    ('Gabriel', NULL, 89),
    ('Roberto', NULL, 90),
    ('Larissa', NULL, 91),
    ('Ana', NULL, 92),
    ('Daniela', NULL, 93),
    ('Gabriel', NULL, 94),
    ('Juliana', NULL, 95),
    ('Larissa', NULL, 96),
    ('Fernanda', NULL, 97),
    ('Gabriel', NULL, 98),
    ('Ana', NULL, 99),
    ('Juliana', NULL, 100);
